name: Build to Github Pages

permissions: 
  id-token: write # This is required for requesting the JWT
  contents: write
  
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.3
      - run: |
          haxelib install lime 
          haxelib install openfl 
          haxelib install flixel
          haxelib install sfxr

      # Runs a set of commands using the runners shell
      - name: Build the HTML5 version
        run: |
          haxelib run lime build html5 
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        if: always()
        with:
          branch: gh-pages
          folder: export/html5/bin
